# This specifies any additional files required by the project
PROJECT_SOURCEFILES=process1.c

# In our case, process2.c is the "main" file
all: process2

TARGET=sky
CONTIKI=/home/victor/kits/contiki
include $(CONTIKI)/Makefile.include
